services:
  - type: web
    name: cypher-node
    runtime: node
    repo: https://github.com/aviator-hackers/cypherNodeMD
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node render-start.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: false
